name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

      - name: Install .NET 6
        run: choco install dotnet-sdk

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release -v normal -p:Version="$(Get-Date -UFormat "%Y.%m%d").$($env:GITHUB_RUN_NUMBER)"

      - name: Pack (Beta)
        run: dotnet pack --include-symbols --no-build -v normal -o $env:GITHUB_WORKSPACE --version-suffix beta
        if: "github.event.release.prerelease"

      - name: Pack (Stable)
        run: dotnet pack --include-symbols --no-build -v normal -o $env:GITHUB_WORKSPACE
        if: "!github.event.release.prerelease"
        
      - name: Publish
        run: dotnet nuget push "$($env:GITHUB_WORKSPACE)\*.nupkg" -k ${{ secrets.NUGET_KEY }} --skip-duplicate