name: Unit Tests

on:
  pull_request:
    branches: master

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  
  orbit_client_id: ${{ secrets.ORBIT_CLIENT_ID }}
  orbit_client_secret: ${{ secrets.ORBIT_CLIENT_SECRET }}
  
  project: './DragonFruit.Common.Data/DragonFruit.Common.Data.csproj'
  testproject: './DragonFruit.Common.Data.Tests/DragonFruit.Common.Data.Tests.csproj'
  
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dotnet: '6.0.x'
            dotnet-tfm: 'net6.0'
            dotnet-test-tfm: 'net6.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: |
          dotnet build $project -c Debug -f ${{ matrix.dotnet-tfm }}
          dotnet build $testproject -c Debug -f ${{ matrix.dotnet-test-tfm }}

      - name: Unit Tests
        run: dotnet test -f ${{ matrix.dotnet-test-tfm }}
